### ISSUE TITLE
FileNotFoundException for System.Diagnostics.DiagnosticSource with version 3.0.0 #237

### ISSUE THREAD

**Issue by jooooel** [RehanSaeed/Serilog.Enrichers.Span#238]
### Describe the bug

If I include this project reference `<PackageReference Include="Serilog.Enrichers.Span" Version="3.0.0" />` and start an `Acitivity` in an Azure Function project, I get the following exception:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at serilog_span_bug.Test.Run(HttpRequest req, ILogger log)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at serilog_span_bug.Test.Run(HttpRequest req, ILogger log)
   at lambda_method110(Closure , Test , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.TaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TaskMethodInvoker.cs:line 21
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
```

I've created a minimal repro by just creating a new Function project, included the package reference, and created a new `Activity`.

I've tried to understand what happens, but I'm afraid it's a bit beyond me. I guess it's some kind of dependency conflict. Even if I explicitly add that reference, I still get the same exception. Downgrading to version `2.3.0` fixes the issue as well.

### Steps to reproduce

1. Clone/Fork https://github.com/jooooel/serilog-span-bug
2. Run the function called `Test` (just F5 in VS/Rider)
3. Invoke the function by going to http://localhost:7071/api/Test in a browser

### Expected behaviour

That there isn't an exception...

**Comment by jooooel** [comment]
I realised this is due to the fact that there is a reference to `System.Diagnostics.DiagnosticSource 7.0.0` in the csproj file and that I'm using it from an Azure Function. So I've open a separate issue [here](https://github.com/Azure/azure-functions-host/issues/8908). I guess you can close this one if you'd like 😊

**Comment by RehanSaeed** [comment]
Thanks for reporting.
